@DotnetPetSearch_HostAddress = http://localhost:5046

### Get Location Data for San Diego's zipcode.
GET {{DotnetPetSearch_HostAddress}}/api/location/zipcode/92101
Accept: application/json

### Get Location Data for San Diego Zoo's coordinates.
GET {{DotnetPetSearch_HostAddress}}/api/location/coordinates?latitude=32.7310927&longitude=-117.1543808
Accept: application/json

